pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: tautulli-dev

  test:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: tautulli-dev
    curl: ':8181/welcome'
    delay: 3
    # Check the version requested in the CSS line.
    # Not ideal but it works for now.
    pipe: >
      sed -nE "/tautulli\\.css/s/.*\\?v([0-9\.]+)\".*/\\1/p" |
      grep -qw "$(label io.spritsail.version.tautulli)"

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    from: tautulli-dev
    repo: spritsail/tautulli
    tags:
      - 'latest'
      - '%label io.spritsail.version.tautulli'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
