---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: tautulli-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    repo: tautulli-dev
    curl: ':8181/welcome'
    delay: 3
    # Check the version requested in the CSS line.
    # Not ideal but it works for now.
    pipe: >
      sed -nE "/tautulli\\.css/s/.*\\?v([0-9\.]+)\".*/\\1/p" |
      grep -qw "$(label io.spritsail.version.tautulli)"

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: tautulli-dev
    repo: spritsail/tautulli
    tags:
    - latest
    - "%label io.spritsail.version.tautulli"
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push
    - tag
---
kind: signature
hmac: 94361ffdd24986cc24c40fc1e0abdd77da02a0a3bdcf9c1795207847aafb32d0

...
