---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: tautulli-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    repo: tautulli-dev
    curl: ':8181/welcome'
    delay: 3
    # Check the version requested in the CSS line.
    # Not ideal but it works for now.
    pipe: >
      sed -nE "/tautulli\\.css/s/.*\\?v([0-9\.]+-beta)\".*/\\1/p" |
      grep -qw "$(label io.spritsail.version.tautulli)"

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: tautulli-dev
    repo: spritsail/tautulli
    tags:
    - beta
    - "%label io.spritsail.version.tautulli | %remsuf beta | %prefix beta | %auto"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - beta
    event:
    - push

---
kind: signature
hmac: b2eb331669826191b872e5f76b9be0d9b16486c369d56cd56d46ac6f060e8b4c

...
