pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - docker build -t plexpy-dev . 

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run --rm -d -p 8181:8181 --user=root devbuild) # Need root for config
      - sleep 10  # Wait for PlexPy to start!
      - docker logs $$CON_NAME
      - curl -sSL --max-time 3 --retry 5 --retry-delay 5 $(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME):8181/welcome  > /dev/null 
      - docker kill $$CON_NAME # Not really needed, but keeps things quick

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    when:
      event: [push, tag, deployment]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - apk add --no-cache openssl
       - echo $DOCKER_USER
       - docker tag plexpy-dev adamant/plexpy:latest
       - docker login -u $DOCKER_USER -p $DOCKER_PASS
       - docker push adamant/plexpy
       - docker rmi plexpy-dev adamant/plexpy
       - echo "CONGRATS! SUCCESSFULLY BUILT SICKRAGE!"
